name: Healthcheck

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  ping_the_app:
    runs-on: ubuntu-18.04
    steps:
      - name: Pokedex healthcheck
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://full-stack-open-pokedex-objh.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true