name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check commit messages for skip
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: |
          if echo "$COMMIT_MESSAGES" | grep -q "#skip"; then
            echo "Skipping tag release step"
            exit 1  # exit with a neutral status to indicate skipping
          fi
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch 
  notify: 
    needs: [tag_release]
    runs-on: ubuntu-20.04
    steps:
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
            text: A new version of Pokedex deploy
            description: to https://full-stack-open-pokedex-objh.onrender.com by locodasi
            severity: info
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        - uses: rjstone/discord-webhook-notify@v1.0.4
          if: failure()
          env:
            COMMIT_SHA: ${{ github.sha }}
            REPO_OWNER: ${{ github.repository_owner }}
            REPO_NAME: ${{ github.repository }}
          uses: rjstone/discord-webhook-notify@v1.0.4
          with:
            description: "Commit [$COMMIT_SHA](https://github.com/$REPO_OWNER/$REPO_NAME/commit/$COMMIT_SHA) by locodasi broke the build :("
              text: Build failed
              severity: error
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
